# Porta dinâmica fornecida pela nuvem
server.port=${PORT:8080}

# Conexão com o banco do Railway usando variáveis de ambiente
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações de JPA
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# IMPORTANTE: Desativa o Docker Compose Support na nuvem
spring.docker.compose.enabled=false